from . import tickets
from . import clients
from . import documents
from . import ai_assistant
from . import reports
from . import equipment_routes
from . import tasks_routes
from . import inspections_routes
from . import nosql_routes
from . import metrics
from . import backup
from . import auth
